apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mydemo-helm-app
  namespace: argocd      # namespace où Argo CD est installé
  annotations:
    argocd-image-updater.argoproj.io/image-list: docker.io/ayoub6000/mydemo
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default

  source:
    repoURL: https://github.com/ayoub60/my-demo-helm
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values.yaml   # facultatif si tu n’as qu’un seul fichier

  destination:
    server: https://kubernetes.default.svc
    namespace: mycompany      # le namespace où ton app sera déployée

  syncPolicy: {}         # => déploiement **manuel**
